url: "https://ewba.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Oƒçistimo Slovenijo digitalnih odpadkov"
lang: "sl"
submitURL: ""
sass:
  style: compressed
